# Generated by Django 5.2.4 on 2025-07-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='c_date',
            field=models.CharField(default=1994, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlogin',
            name='c_name',
            field=models.CharField(default=1994, max_length=100),
            preserve_default=False,
        ),
    ]
