# Generated by Django 5.2.4 on 2025-07-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userlogin_c_date_userlogin_c_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='c_date',
            new_name='c_data',
        ),
    ]
