# Generated by Django 5.2.4 on 2025-07-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_c_date_userlogin_c_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='c_data',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='c_name',
        ),
    ]
